### ISSUE TITLE
unresolved dependency 

### ISSUE THREAD

**Issue by Kesavan21u** [master/spark-stemming#3]
when installing the sbt file in the Intellij idea. It shows error like Unresolved dependency.

**Comment by mohammedi-haroune** [comment]
same case for me, @Kesavan21u did you resolved the issue ?

**Comment by Kesavan21u** [comment]
@mohammedi-haroune  No, I used a standford coreNLP Lemmatization in my project

**Comment by mohammedi-haroune** [comment]
@Kesavan21u thanks for your response I'll take a look

**Comment by Timoeller** [comment]
I also stumbled upon this problem.
You need to add another resolver to your build.sbt:
resolvers ++= Seq("spark-stemming" at "https://dl.bintray.com/spark-packages/maven/")

and import dependency: "master" % "spark-stemming" % "0.1.1"
not version 0.1.2
