### ISSUE TITLE
Fetching spark-stemming from Maven

### ISSUE THREAD

**Issue by LambdaVex** [master/spark-stemming#4]
Maven doesn't seem to be able to fetch spark-stemming from the repository when adding the script 
`<dependency>
    <groupId>master</groupId>
    <artifactId>spark-stemming_2.10</artifactId>
    <version>0.1.2</version>
</dependency>`
to the Pom file.
It returns an error that the dependencies could not be resolved

**Comment by master** [comment]
Should be fixed in 0.2.0
